post commit hook test

diff --git a/a b/a
--- a/a
+++ b/a
@@ -1,19 +1,22 @@
 #!/usr/bin/env bash
-#git <a/914edad>
-#nix <1656600941>
-#hbc <1b4405c>
+#git <a/76f0927>
+#nix <1656641273>
+#hbc <f123e56>
 #src <ask.sh>
 #src <color.sh>
 #src <crypto.sh>
 #src <date.sh>
 #src <hash.sh>
+#src <is.sh>
+#src <lock.sh>
 #src <log.sh>
 #src <panic.sh>
+#src <safety.sh>
 #src <trace.sh>
 #src <var.sh>
 
 #-------------------------------------------------------------------------------- BEGIN SRC CODE
-ask::yes(){
+ask::yes() {
 	local ASK_FUNC_RESPONSE || return 44
 	read -r ASK_FUNC_RESPONSE
 	case $ASK_FUNC_RESPONSE in
@@ -21,7 +24,7 @@ ask::yes(){
 		*) return 2 ;;
 	esac
 }
-ask::no(){
+ask::no() {
 	local ASK_FUNC_RESPONSE || return 44
 	read -r ASK_FUNC_RESPONSE
 	case $ASK_FUNC_RESPONSE in
@@ -29,151 +32,203 @@ ask::no(){
 		*) return 0 ;;
 	esac
 }
-ask::sudo(){
+ask::sudo() {
 	sudo -v
-	return
 }
-color::black(){ printf "\033[0;30m" ;}
-color::red(){ printf "\033[0;31m" ;}
-color::green(){ printf "\033[0;32m" ;}
-color::yellow(){ printf "\033[0;33m" ;}
-color::blue(){ printf "\033[0;34m" ;}
-color::purple(){ printf "\033[0;35m" ;}
-color::cyan(){ printf "\033[0;36m" ;}
-color::white(){ printf "\033[0;37m" ;}
-color::bblack(){ printf "\033[1;30m" ;}
-color::bred(){ printf "\033[1;31m" ;}
-color::bgreen(){ printf "\033[1;32m" ;}
-color::byellow(){ printf "\033[1;33m" ;}
-color::bblue(){ printf "\033[1;34m" ;}
-color::bpurple(){ printf "\033[1;35m" ;}
-color::bcyan(){ printf "\033[1;36m" ;}
-color::bwhite(){ printf "\033[1;37m" ;}
-color::iblack(){ printf "\033[0;90m" ;}
-color::ired(){ printf "\033[0;91m" ;}
-color::igreen(){ printf "\033[0;92m" ;}
-color::iyellow(){ printf "\033[0;93m" ;}
-color::iblue(){ printf "\033[0;94m" ;}
-color::ipurple(){ printf "\033[0;95m" ;}
-color::icyan(){ printf "\033[0;96m" ;}
-color::iwhite(){ printf "\033[0;97m" ;}
-color::off(){ printf "\033[0m" ;}
-crypto::bytes(){
+color::black() { printf "\033[0;30m" ;}
+color::red() { printf "\033[0;31m" ;}
+color::green() { printf "\033[0;32m" ;}
+color::yellow() { printf "\033[0;33m" ;}
+color::blue() { printf "\033[0;34m" ;}
+color::purple() { printf "\033[0;35m" ;}
+color::cyan() { printf "\033[0;36m" ;}
+color::white() { printf "\033[0;37m" ;}
+color::bblack() { printf "\033[1;30m" ;}
+color::bred() { printf "\033[1;31m" ;}
+color::bgreen() { printf "\033[1;32m" ;}
+color::byellow() { printf "\033[1;33m" ;}
+color::bblue() { printf "\033[1;34m" ;}
+color::bpurple() { printf "\033[1;35m" ;}
+color::bcyan() { printf "\033[1;36m" ;}
+color::bwhite() { printf "\033[1;37m" ;}
+color::iblack() { printf "\033[0;90m" ;}
+color::ired() { printf "\033[0;91m" ;}
+color::igreen() { printf "\033[0;92m" ;}
+color::iyellow() { printf "\033[0;93m" ;}
+color::iblue() { printf "\033[0;94m" ;}
+color::ipurple() { printf "\033[0;95m" ;}
+color::icyan() { printf "\033[0;96m" ;}
+color::iwhite() { printf "\033[0;97m" ;}
+color::off() { printf "\033[0m" ;}
+crypto::bytes() {
 	[[ $# = 0 || $# -gt 1 ]] && return 1
 	head -c $1 /dev/random
 }
-crypto::num(){
+crypto::num() {
 	[[ $# = 0 || $# -gt 1 ]] && return 1
 	shuf -i 0-$1 -n 1
 }
-date::unix::translate(){
+date::unix_translate() {
 	if [[ -p /dev/stdin ]]; then
-		local i || return 44
+		local i || return 11
 		for i in $(</dev/stdin); do
-			date -d @"$i" || return 2
+			date -d @"$i" || return 22
 		done
 		return 0
-	elif [[ $# = 0 ]]; then
-		return 1
 	fi
+	[[ $# = 0 ]] && return 33
 	while [[ $# != 0 ]]; do
-		date -d @"$1" || return 2
+		date -d @"$1" || return 44
 		shift
 	done
 	return 0
 }
-date::unix(){ printf "%s\n" "$EPOCHSECONDS" ;}
-date::time(){ date +"%T" ;}
-date::calendar(){ date +"%Y-%m-%d" ;}
-date::now(){ date +"%Y-%m-%d %T" ;}
-date::year(){ date +"%Y" ;}
-date::month(){ date +"%m" ;}
-date::day(){ date +"%d" ;}
-date::hour(){ date +"%H" ;}
-date::minute(){ date +"%M" ;}
-date::second(){ date +"%S" ;}
-hash::md5(){
-	set -o pipefail || return 44
+date::unix() { printf "%s\n" "$EPOCHSECONDS" ;}
+date::time() { date +"%T" ;}
+date::calendar() { date +"%Y-%m-%d" ;}
+date::now() { date +"%Y-%m-%d %T" ;}
+date::year() { date +"%Y" ;}
+date::month() { date +"%m" ;}
+date::day() { date +"%d" ;}
+date::hour() { date +"%H" ;}
+date::minute() { date +"%M" ;}
+date::second() { date +"%S" ;}
+hash::md5() {
+	set -o pipefail || return 11
 	if [[ -p /dev/stdin ]]; then
-		local i || return 44
+		local i || return 22
 		for i in $(</dev/stdin); do
-			printf "%s" "$i" | md5sum | tr -d ' -' || return 2
+			printf "%s" "$i" | md5sum | tr -d ' -' || return 33
 		done
 		set +o pipefail && return 0 || return 44
 	elif [[ $# = 0 ]]; then
-		set +o pipefail || return 44
+		set +o pipefail || return 55
 		return 1
 	fi
 	while [[ $# != 0 ]]; do
-		printf "%s" "$1" | md5sum | tr -d ' -' || return 2
+		printf "%s" "$1" | md5sum | tr -d ' -' || return 66
 		shift
 	done
-	set +o pipefail && return 0 || return 44
+	set +o pipefail && return 0 || return 77
 }
-hash::sha1(){
-	set -o pipefail || return 44
+hash::sha1() {
+	set -o pipefail || return 11
 	if [[ -p /dev/stdin ]]; then
-		local i || return 44
+		local i || return 22
 		for i in $(</dev/stdin); do
-			printf "%s" "$i" | sha1sum | tr -d ' -' || return 2
+			printf "%s" "$i" | sha256sum | tr -d ' -' || return 33
 		done
 		set +o pipefail && return 0 || return 44
 	elif [[ $# = 0 ]]; then
-		set +o pipefail || return 44
+		set +o pipefail || return 55
 		return 1
 	fi
 	while [[ $# != 0 ]]; do
-		printf "%s" "$1" | sha1sum | tr -d ' -' || return 2
+		printf "%s" "$1" | sha256sum | tr -d ' -' || return 66
 		shift
 	done
-	set +o pipefail && return 0 || return 44
+	set +o pipefail && return 0 || return 77
 }
-hash::sha256(){
-	set -o pipefail || return 44
+hash::sha256() {
+	set -o pipefail || return 11
 	if [[ -p /dev/stdin ]]; then
-		local i || return 44
+		local i || return 22
 		for i in $(</dev/stdin); do
-			printf "%s" "$i" | sha256sum | tr -d ' -' || return 2
+			printf "%s" "$i" | sha256sum | tr -d ' -' || return 33
 		done
 		set +o pipefail && return 0 || return 44
 	elif [[ $# = 0 ]]; then
-		set +o pipefail || return 44
+		set +o pipefail || return 55
 		return 1
 	fi
 	while [[ $# != 0 ]]; do
-		printf "%s" "$1" | sha256sum | tr -d ' -' || return 2
+		printf "%s" "$1" | sha256sum | tr -d ' -' || return 66
 		shift
 	done
-	set +o pipefail && return 0 || return 44
+	set +o pipefail && return 0 || return 77
 }
-hash::sha512(){
-	set -o pipefail || return 44
+hash::sha512() {
+	set -o pipefail || return 11
 	if [[ -p /dev/stdin ]]; then
-		local i || return 44
+		local i || return 22
 		for i in $(</dev/stdin); do
-			printf "%s" "$i" | sha512sum | tr -d ' -' || return 2
+			printf "%s" "$i" | sha512sum | tr -d ' -' || return 33
 		done
 		set +o pipefail && return 0 || return 44
 	elif [[ $# = 0 ]]; then
-		set +o pipefail || return 44
+		set +o pipefail || return 55
 		return 1
 	fi
 	while [[ $# != 0 ]]; do
-		printf "%s" "$1" | sha512sum | tr -d ' -' || return 2
+		printf "%s" "$1" | sha512sum | tr -d ' -' || return 66
 		shift
 	done
-	set +o pipefail && return 0 || return 44
+	set +o pipefail && return 0 || return 77
 }
-log::dot(){ printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\r" "$@" ;}
-log::prog(){ printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\n" "$@" ;}
-log::tab(){ printf "\033[0m         %s\n" "$@" ;}
-log::ok(){ printf "\033[1;32m[  OK  ]\033[0m %s\n" "$@" ;}
-log::info(){ printf "\033[1;37m[ INFO ]\033[0m %s\n" "$@" ;}
-log::warn(){ printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
-log::fail(){ printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
-log::danger(){ printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
+is::int() {
+	if [[ -p /dev/stdin ]]; then
+		local i || return 11
+		for i in $(</dev/stdin); do
+			[ $i -eq $i ] &>/dev/null || return 22
+		done
+		return 0
+	fi
+	[[ $# = 0 ]] && return 33
+	local i || return 44
+	for i in $@; do
+		[ $i -eq $i ] &>/dev/null || return 55
+	done
+}
+is::int_pos() {
+	if [[ -p /dev/stdin ]]; then
+		local i || return 11
+		for i in $(</dev/stdin); do
+			[ $i -gt -1 ] &>/dev/null || return 22
+			[ $i -eq $i ] &>/dev/null || return 33
+		done
+		return 0
+	fi
+	[[ $# = 0 ]] && return 44
+	local i || return 55
+	for i in $@; do
+		[ $i -gt -1 ] &>/dev/null || return 66
+		[ $i -eq $i ] &>/dev/null || return 77
+	done
+}
+is::int_neg() {
+	if [[ -p /dev/stdin ]]; then
+		local i || return 11
+		for i in $(</dev/stdin); do
+			[ $i -lt 0 ] &>/dev/null || return 22
+			[ $i -eq $i ] &>/dev/null || return 33
+		done
+		return 0
+	fi
+	[[ $# = 0 ]] && return 44
+	local i || return 55
+	for i in $@; do
+		[ $i -lt 0 ] &>/dev/null || return 66
+		[ $i -eq $i ] &>/dev/null || return 77
+	done
+}
+lock::alloc() {
+	exec 200<"$0" || return 2
+	flock -n 200 || return 66
+	return 0
+}
+lock::free() {
+	exec 200<&-
+}
+log::dot() { printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\n" "$@" ;}
+log::prog() { printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\r" "$@" ;}
+log::tab() { printf "\033[0m         %s\n" "$@" ;}
+log::ok() { printf "\033[1;32m[  OK  ]\033[0m %s\n" "$@" ;}
+log::info() { printf "\033[1;37m[ INFO ]\033[0m %s\n" "$@" ;}
+log::warn() { printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
+log::fail() { printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
+log::danger() { printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
 panic() {
-	local PANIC_EXIT_CODE="$?" || exit 98
+	local PANIC_EXIT_CODE="$?" TRACE_FUNC=("${BASH_LINENO[@]}") || exit 98
 	printf "\033[1;91m%s\n"\
 		":::::::::::::::::"\
 		":     panic     :"\
@@ -182,12 +237,19 @@ panic() {
 	TRACE_CMD_NUM="${BASH_LINENO[0]}"
 	local PANIC_CMD
 	PANIC_CMD="$(sed -n "$TRACE_CMD_NUM p" $0)"
-	printf "\033[1;94m%s\033[0m%s%s\n" "[  \$_  ] " "${BASH_LINENO[0]}: " "$(printf "%s" "$PANIC_CMD" | tr -d '\t')"
-	printf "\033[1;92m%s\033[0m%s\n" "[ func ] " "${BASH_LINENO[1]}: ${FUNCNAME[1]}()"
-	printf "\033[1;97m%s\033[0m%s\n" "[ file ] " "${BASH_SOURCE[-1]}"
-	printf "\033[1;91m%s\033[0m%s\n" "[ code ] " "$PANIC_EXIT_CODE"
-	printf "\033[1;96m%s\033[0m%s\n" "[ unix ] " "$EPOCHSECONDS"
-	printf "\033[1;93m%s\033[0m%s\n" "[  wd  ] " "$PWD"
+	printf "\033[1;97m%s\033[0m%s\n" "[file] " "${BASH_SOURCE[-1]}"
+	printf "\033[1;91m%s\033[0m%s\n" "[code] " "$PANIC_EXIT_CODE"
+	printf "\033[1;96m%s\033[0m%s\n" "[unix] " "$EPOCHSECONDS"
+	printf "\033[1;93m%s\033[0m%s\n" "[ wd ] " "$PWD"
+	printf "\033[1;94m%s\033[0m%s%s\n" "[ \$_ ] " "$TRACE_CMD_NUM: " "$(printf "%s" "$PANIC_CMD" | tr -d '\t')"
+	local f
+	local i=1
+	TRACE_FUNC=("${TRACE_FUNC[@]:1}")
+	for f in ${TRACE_FUNC[@]}; do
+		[[ $f = 0 ]] && break
+		printf "\033[1;92m%s\033[0m%s\n" "[func] " "${f}: ${FUNCNAME[${i}]}()"
+		((i++))
+	done
 	if [[ $TRACE_CMD_NUM -lt 5 ]]; then
 		printf "\033[1;90m%s\n\033[1;97m%s\n\033[1;90m%s\033[0;m\n" \
 		"$(sed -n "1,$((TRACE_CMD_NUM-1)) p" $0 | nl -s' ' -ba -v 1)" \
@@ -199,15 +261,17 @@ panic() {
 		"$(echo "$PANIC_CMD" | nl -s' ' -ba -v $TRACE_CMD_NUM)" \
 		"$(sed -n "$((TRACE_CMD_NUM+1)),$((TRACE_CMD_NUM+4)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM+1)))"
 	fi
-	[[ $1 ]] && exit $1 || exit 99
+	[[ $1 =~ ^[0-9]+$ ]] && exit $1 || exit 99
 }
-___BEGIN___ERROR___TRACE___(){
+safety::bash() { [[ ${BASH_VERSINFO[0]} -ge 5 ]] ;}
+safety::gnu_linux() { [[ $OSTYPE = linux-gnu* ]] ;}
+___BEGIN___ERROR___TRACE___() {
 	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="${BASH_LINENO[@]}" TRACE_CMD_NUM="$LINENO" TRACE_CODE="$?" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 11
 	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 22
 	set -E -e -o pipefail || exit 33
 	return 0
 }
-___ENDOF___ERROR___TRACE___(){
+___ENDOF___ERROR___TRACE___() {
 	if [[ -z $TRACE_CODE ]]; then
 		set +E +eo pipefail || exit 44
 		trap - ERR || exit 55
